name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Generate build number
      id: buildnumber
      uses: einaregilsson/build-number@v1
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100
        bdnumber: ${{steps.buildnumber.outputs.build_number}}
    - name: Build with dotnet
      run: dotnet build --configuration Release
    - name: Publish to Nexus
      env:
        super_secret: ${{ secrets.NEXUS }} 
      run: dotnet pack --version-suffix $bdnumber -c Release -o ./ && dotnet nuget push -s https://nexus.qaybe.de/repository/nuget-hosted/ -k $super_secret *.nupkg && rm *.nupkg

